New approach for ansible installation

diff --git a/.github/workflows/comp-wflow.yml b/.github/workflows/comp-wflow.yml
--- a/.github/workflows/comp-wflow.yml
+++ b/.github/workflows/comp-wflow.yml
@@ -1,55 +1,42 @@
-# This is a basic workflow to help you get started with Actions
+name: Complete Workflow
 
-name: Complete workflow
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
-  # Allows you to run this workflow manually from the Actions tab
-#  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: self-hosted
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      # Runs a single command using the runners shell
-      - name: Installing dependencies
+      - name: Install dependencies
         run: |
-          echo "The processes are installing in sequential order"
-          sudo apt update -y
-          sudo apt install git -y
-          sudo apt install python3-pip -y
-          pip install pywinrm
-          
-      - name: Installing Ansible
-        run: |
-          sudo apt-get update && sudo apt-get install software-properties-common -y && sudo apt-add-repository --yes --update ppa:ansible/ansible
+          echo "Process is in sequential order"
           sudo apt-get update -y
-          sudo apt-get install ansible -y
+          sudo apt-get install git -y
+          sudo apt-get install python3-pip -y
+          pip install pywinrm
 
-      - name: Setting the config file
+      - name: Install ansible
         run: |
-          cp -r ansible.cfg /etc/ansible/
-          
-      - name: Running Playbook
+          echo "Ansible installation starts"
+          sudo apt-get update && sudo apt-get install software-properties-common -y && sudo apt-add-repository --yes --update ppa:ansible/ansible
+          if ! ansible --version >/dev/null 2>&1; then
+            echo "Ansible not installed. Workflow stopped"
+          else
+            echo "Ansible is installed"
+          fi
+
+      - name: Checking ansible ping and running playbook
         run: |
+          ansible -m localhost ping
           ansible-playbook docker-create.yaml
+          if ! docker --version >/dev/null 2>&1; then
+            echo "Playbook failed"
+          else
+            echo "Docker installation completed"
+          fi
 
-      # Runs a set of commands using the runners shell
-     # - name: Run a multi-line script
-      #  run: |
-       #   echo Add other actions to build,
-        #  echo test, and deploy your project.
